version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_expensemanager
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: expensemanager_api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/expensemanager
    restart: always

volumes:
  mongo_data:
